### ISSUE TITLE
Q: Advertising UIOP for filesystem interaction?

### ISSUE THREAD

**Issue by epipping** [fare/asdf2017#2]
The document currently says:

> UIOP [provides] robust utilities that abstract away the differences between
> implementations and between operating systems;
> it notably makes it possible to use pathnames and access the filesystem
> in a portable way.

At the same time, it later acknowledges

> For full coverage of the capabilities offered by operating systems,
> one may thus have to use a library such as **osicat** or **IOLib**,
> that will invoke a C compiler or link C libraries via the **CFFI** library,
> as needed to build or access low-level extensions to the Lisp system.

As fond as I am of UIOP and believe its quality to be generally high, I would not advertise filesystem interaction as one of its strengths; rather, I would actively encourage anyone who interacts with the filesystem to use **osicat** unless they absolutely cannot, which I expect seldom to be the case. Because getting symlinks right on Linux should be something rather basic. And only in the CL world is it not. And UIOP doesn't get them right, even on non-obscure implementations. It's entirely understandable that it cannot, but I think we should not hide that fact; by doing so, we risk burning users who would then give UIOP a bad reputation.

So I'd like to change those two paragraphs such that filesystem interaction is not listed as a selling feature of UIOP unconditionally and that **osicat** and **iolib** are explicitly connected to getting e.g. symlinks right (because right now it's not clear what one would gain from using them).

What do you think?

**Comment by fare** [comment]
OK, I pushed something to that effect. PTAL.

I also made you and Robert committers.

Finally, mind that the limit for demonstrations is 2 pages. We can aim at a "tutorial" with a 4 page limit, or an "article" with an 8 page limit, but there's a higher bar on content.
