### ISSUE TITLE
How does the scribble compilation work?

### ISSUE THREAD

**Issue by rpgoldman** [fare/asdf2017#3]
Here's what I get:
{{{
 $ make asdf2017.pdf
time scribble --dest-name asdf2017.pdf --pdf asdf2017.scrbl
standard-module-name-resolver: collection not found
  for module path: scribble/acmart/lang/reader
  collection: "scribble/acmart/lang"
  in collection directories:
   /Users/rpg/Library/Racket/6.7/collects
   /Applications/Racketv6.7/collects
   ... [160 additional linked and package directories]
  context...:
   show-collection-err
   standard-module-name-resolver
   /Applications/Racketv6.7/collects/syntax/module-reader.rkt:249:18: loop
   /Applications/Racketv6.7/collects/syntax/module-reader.rkt:296:4: -read-syntax
   standard-module-name-resolver
   /Applications/Racketv6.7/share/pkgs/scribble-lib/scribble/run.rkt:143:24
   ...cket/cmdline.rkt:179:51
   /Applications/Racketv6.7/share/pkgs/scribble-lib/scribble/run.rkt: [running body]
        0.58 real         0.28 user         0.10 sys
make: *** [asdf2017.pdf] Error 1
}}}

I put your acmart and acmart-master directories in `~/Libraries/Applications/Racket/6.7` but no joy.

I'm not sure I see what's so wrong with LaTeX that we need to use this side dialect....

**Comment by fare** [comment]
I pushed some instructions in the `README.md`

Note that if you already installed acmart, you need to `git pull`, because I just made crucial changes to support the CCS indexing.
