### ISSUE TITLE
Still can't scribble-compile

### ISSUE THREAD

**Issue by rpgoldman** [fare/asdf2017#5]
Neither `make asdf2017.pdf` nor `make asdf2017.html`work for me.

I have pulled the acmart latest version and installed it and that does not appear to help.  The error I get is this (Alexander and the terrible, horrible, cryptic, very bad, no good error message): 
```
asdf2017.scrbl:57:1: category: unbound identifier in module
  in: category
```
I'm not sure if it's `category` it doesn't grok, or some sub-form of this
```
@category["D.2.3" "Software Engineering"]{Coding Tools and Techniques}
```

**Comment by fare** [comment]
This form does NOT exist anymore in the latest asdf2017 commit `22c5096`

**Comment by fare** [comment]
Note that if you have trouble compiling, I maintain a pre-compiled version at http://fare.tunes.org/files/asdf2017/asdf2017.pdf
